import fs from 'fs';
import path from 'path';
import os from 'os';
import { execSync } from 'child_process';
import exifr from 'exifr';

const PUBLIC_PHOTOS_DIR = path.resolve('public/photos');
const DISPLAY_DIR = path.join(PUBLIC_PHOTOS_DIR, 'display');
const THUMB_DIR = path.join(PUBLIC_PHOTOS_DIR, 'thumb');

fs.mkdirSync(DISPLAY_DIR, { recursive: true });
fs.mkdirSync(THUMB_DIR, { recursive: true });

function formatExposureTime(sec) {
  if (!sec) return '1/250s';
  if (sec >= 1) return `${Math.round(sec * 10) / 10}s`;
  const denom = Math.round(1 / sec);
  return `1/${denom}s`;
}

function formatFNumber(f) {
  if (!f) return 'ƒ/1.4';
  const rounded = Math.round(f * 10) / 10;
  return Number.isInteger(rounded) ? `ƒ/${rounded}.0` : `ƒ/${rounded}`;
}

function resolveUserPath(inputPath) {
  if (inputPath.startsWith('~')) {
    return path.join(os.homedir(), inputPath.slice(1));
  }
  return path.resolve(inputPath);
}

function loadExistingPhotos() {
  const filePath = path.resolve('src/data/photos.ts');
  if (!fs.existsSync(filePath)) return [];
  const content = fs.readFileSync(filePath, 'utf8');
  const match = content.match(/export const photos: Photo\[\] = (\[[\s\S]*?\]);/);
  if (match) {
    try {
      return JSON.parse(match[1]);
    } catch (err) {
      console.warn('Failed to parse existing photos from photos.ts:', err.message);
    }
  }
  return [];
}

async function processSinglePhoto({ inputPath, seriesName, profileName = 'Reala Ace · RAW Edit' }) {
  const file = path.basename(inputPath);
  const ext = path.extname(file).toLowerCase();
  const baseName = path.basename(file, ext).toLowerCase();
  const id = `${seriesName.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-${baseName}`;
  const displayFileName = `${id}.jpg`;
  const thumbFileName = `${id}.jpg`;

  const displayPath = path.join(DISPLAY_DIR, displayFileName);
  const thumbPath = path.join(THUMB_DIR, thumbFileName);
  const tinyPath = `/tmp/tiny-${id}.jpg`;

  console.log(`Processing: ${file} -> ${id}`);

  // Sips resizing (only if not already generated to save time)
  if (!fs.existsSync(displayPath)) {
    execSync(`sips -Z 2048 "${inputPath}" --out "${displayPath}" > /dev/null 2>&1`);
  }
  if (!fs.existsSync(thumbPath)) {
    execSync(`sips -Z 800 "${inputPath}" --out "${thumbPath}" > /dev/null 2>&1`);
  }
  execSync(`sips -Z 20 "${inputPath}" --out "${tinyPath}" > /dev/null 2>&1`);

  const blurDataUrl = 'data:image/jpeg;base64,' + fs.readFileSync(tinyPath).toString('base64');
  try { fs.unlinkSync(tinyPath); } catch {}

  // Parse dimensions with sips
  const dimOutput = execSync(`sips -g pixelWidth -g pixelHeight "${displayPath}"`).toString();
  const widthMatch = dimOutput.match(/pixelWidth:\s*(\d+)/);
  const heightMatch = dimOutput.match(/pixelHeight:\s*(\d+)/);
  const width = widthMatch ? parseInt(widthMatch[1], 10) : 2048;
  const height = heightMatch ? parseInt(heightMatch[1], 10) : 1365;
  const aspectRatio = Math.round((width / height) * 1000) / 1000;

  // Parse EXIF with exifr
  let exif = {};
  try {
    exif = (await exifr.parse(inputPath, true)) || {};
  } catch (err) {
    console.warn(`Could not read EXIF for ${file}:`, err.message);
  }

  const camera = exif.Model ? `FUJIFILM ${exif.Model.replace(/^FUJIFILM\s*/i, '')}` : 'FUJIFILM X-T5';
  let lens = exif.LensModel || 'XF23mmF1.4 R LM WR';
  if (lens.includes('23.0 mm f/1.4')) {
    lens = 'XF23mmF1.4 R LM WR';
  }
  const aperture = formatFNumber(exif.FNumber || 1.4);
  const shutterSpeed = formatExposureTime(exif.ExposureTime || 0.004);
  const iso = exif.ISO ? `ISO ${exif.ISO}` : 'ISO 125';
  const focalLength = exif.FocalLength ? `${Math.round(exif.FocalLength)}mm` : '23mm';

  let dateTaken = '2025';
  if (exif.CreateDate instanceof Date && !isNaN(exif.CreateDate.getTime())) {
    dateTaken = exif.CreateDate.toISOString().split('T')[0];
  }

  return {
    id,
    series: seriesName,
    fileNumber: path.basename(file, path.extname(file)),
    displayUrl: `/photos/display/${displayFileName}`,
    thumbUrl: `/photos/thumb/${thumbFileName}`,
    width,
    height,
    aspectRatio,
    blurDataUrl,
    camera,
    lens,
    aperture,
    shutterSpeed,
    iso,
    focalLength,
    profile: profileName,
    dateTaken,
    featured: false,
  };
}

function writePhotosFile(allPhotos) {
  // Deduplicate by ID
  const uniqueMap = new Map();
  for (const p of allPhotos) {
    uniqueMap.set(p.id, p);
  }
  const photosArray = Array.from(uniqueMap.values());

  const seriesCounts = {};
  for (const p of photosArray) {
    seriesCounts[p.series] = (seriesCounts[p.series] || 0) + 1;
  }

  const seriesList = [
    { id: 'all', name: 'All Works', count: photosArray.length },
    ...Object.entries(seriesCounts).map(([name, count]) => ({
      id: name.toLowerCase().replace(/[^a-z0-9]+/g, '-'),
      name,
      count
    }))
  ];

  const fileContent = `// Auto-generated by scripts/ingest.mjs
// Titles are optional: if omitted, the UI displays clean series & camera details.
// Profile defaults to Reala Ace · RAW Edit, or can be customized per photo.

export interface Photo {
  id: string;
  title?: string;
  series: string;
  fileNumber: string;
  displayUrl: string;
  thumbUrl: string;
  width: number;
  height: number;
  aspectRatio: number;
  blurDataUrl: string;
  camera: string;
  lens: string;
  aperture: string;
  shutterSpeed: string;
  iso: string;
  focalLength: string;
  profile?: string;
  dateTaken: string;
  featured: boolean;
}

export const photos: Photo[] = ${JSON.stringify(photosArray, null, 2)};

export const seriesList = ${JSON.stringify(seriesList, null, 2)};
`;

  fs.mkdirSync(path.resolve('src/data'), { recursive: true });
  fs.writeFileSync(path.resolve('src/data/photos.ts'), fileContent);
  console.log(`\nSuccessfully updated src/data/photos.ts with ${photosArray.length} photos across ${Object.keys(seriesCounts).length} series!`);
}

async function run() {
  const args = process.argv.slice(2);

  // If a directory is passed: node scripts/ingest.mjs <dir> [series-name]
  if (args.length > 0) {
    const rawPath = args[0];
    const targetDir = resolveUserPath(rawPath);

    if (!fs.existsSync(targetDir)) {
      console.error(`Directory not found: ${targetDir}`);
      process.exit(1);
    }

    const seriesName = args[1] || path.basename(targetDir);
    console.log(`\n--- Ingesting photos from: ${targetDir} as Series: "${seriesName}" ---`);

    // Load existing photos reliably by parsing photos.ts
    const existingPhotos = loadExistingPhotos();
    console.log(`Found ${existingPhotos.length} existing photos in library.`);

    const files = fs.readdirSync(targetDir).filter(f => /\.(jpe?g|png)$/i.test(f));
    if (files.length === 0) {
      console.log(`No images found in ${targetDir}`);
      return;
    }

    const newPhotos = [];
    for (const file of files) {
      const p = await processSinglePhoto({
        inputPath: path.join(targetDir, file),
        seriesName,
      });
      newPhotos.push(p);
    }

    writePhotosFile([...existingPhotos, ...newPhotos]);
    return;
  }

  // Default: Process baseline Hokkaido & Korea selection
  const HOKKAIDO_DIR = resolveUserPath('~/Desktop/Untitled Export/Hokkaido 2025');
  const KOREA_DIR = resolveUserPath('~/Desktop/Untitled Export/Korea 2025');

  const defaultList = [
    { series: 'Hokkaido 2025', dir: HOKKAIDO_DIR, file: 'DSCF2592.jpg' },
    { series: 'Hokkaido 2025', dir: HOKKAIDO_DIR, file: 'DSCF2621.jpg' },
    { series: 'Hokkaido 2025', dir: HOKKAIDO_DIR, file: 'DSCF2732.jpg' },
    { series: 'Hokkaido 2025', dir: HOKKAIDO_DIR, file: 'DSCF2792.jpg' },
    { series: 'Hokkaido 2025', dir: HOKKAIDO_DIR, file: 'DSCF2836.jpg' },
    { series: 'Hokkaido 2025', dir: HOKKAIDO_DIR, file: 'DSCF2972.jpg' },
    { series: 'Korea 2025', dir: KOREA_DIR, file: 'DSCF2059.JPG' },
    { series: 'Korea 2025', dir: KOREA_DIR, file: 'DSCF2110.jpg' },
    { series: 'Korea 2025', dir: KOREA_DIR, file: 'DSCF2175.jpg' },
    { series: 'Korea 2025', dir: KOREA_DIR, file: 'DSCF2220.jpg' },
    { series: 'Korea 2025', dir: KOREA_DIR, file: 'DSCF2267.jpg' },
    { series: 'Korea 2025', dir: KOREA_DIR, file: 'DSCF2316.jpg' },
  ];

  const existingPhotos = loadExistingPhotos();
  const results = [];
  for (const item of defaultList) {
    const p = await processSinglePhoto({
      inputPath: path.join(item.dir, item.file),
      seriesName: item.series,
    });
    results.push(p);
  }

  writePhotosFile([...existingPhotos, ...results]);
}

run().catch(console.error);
